# Walmart Cleaning

STEP 1: Load Data

In [1]:
# use pands & numpy libraries
import pandas as pd

In [2]:
# Load dataset
sales = pd.read_csv("sales data-set.csv")
features = pd.read_csv("Features data set.csv")
stores = pd.read_csv("stores data-set.csv")

STEP 2: Initial Data Exploration

In [3]:
# Preview first rows
sales.head()

   Store  Dept        Date  Weekly_Sales  IsHoliday
0      1     1  05/02/2010      24924.50      False
1      1     1  12/02/2010      46039.49       True
2      1     1  19/02/2010      41595.55      False
3      1     1  26/02/2010      19403.54      False
4      1     1  05/03/2010      21827.90      False

In [4]:
features.head()

,Store,Date,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment,IsHoliday
0,1,05/02/2010,42.31,2.572,NaN,NaN,NaN,NaN,NaN,211.096358,8.106,False
1,1,12/02/2010,38.51,2.548,NaN,NaN,NaN,NaN,NaN,211.242170,8.106,True
2,1,19/02/2010,39.93,2.514,NaN,NaN,NaN,NaN,NaN,211.289143,8.106,False
3,1,26/02/2010,46.63,2.561,NaN,NaN,NaN,NaN,NaN,211.319643,8.106,False
4,1,05/03/2010,46.50,2.625,NaN,NaN,NaN,NaN,NaN,211.350143,8.106,False

In [5]:
stores.head()

   Store Type    Size
0      1    A  151315
1      2    A  202307
2      3    B   37392
3      4    A  205863
4      5    B   34875

In [8]:
# Number of rows and columns
sales.shape

(421570, 5)

In [7]:
features.shape

(8190, 12)

In [9]:
stores.shape

(45, 3)

In [10]:
# Display column names
sales.columns

Index(['Store', 'Dept', 'Date', 'Weekly_Sales', 'IsHoliday'], dtype='object')

In [11]:
features.columns

Index(['Store', 'Date', 'Temperature', 'Fuel_Price', 'MarkDown1', 'MarkDown2',
       'MarkDown3', 'MarkDown4', 'MarkDown5', 'CPI', 'Unemployment',
       'IsHoliday'],
      dtype='object')

In [12]:
stores.columns

Index(['Store', 'Type', 'Size'], dtype='object')

In [13]:
# Data types and missing values
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 421570 entries, 0 to 421569
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Store         421570 non-null  int64
 1   Dept          421570 non-null  int64
 2   Date          421570 non-null  object
 3   Weekly_Sales  421570 non-null  float64
 4   IsHoliday     421570 non-null  bool
dtypes: bool(1), float64(1), int64(2), object(1)
memory usage: 13.3+ MB

In [14]:
features.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8190 entries, 0 to 8189
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Store         8190 non-null   int64
 1   Date          8190 non-null   object
 2   Temperature   8190 non-null   float64
 3   Fuel_Price    8190 non-null   float64
 4   MarkDown1     4032 non-null   float64
 5   MarkDown2     2921 non-null   float64
 6   MarkDown3     3613 non-null   float64
 7   MarkDown4     3464 non-null   float64
 8   MarkDown5     4050 non-null   float64
 9   CPI           7605 non-null   float64
 10  Unemployment  7605 non-null   float64
 11  IsHoliday     8190 non-null   bool
dtypes: bool(1), float64(9), int64(1), object(1)
memory usage: 712.0+ KB

In [15]:
stores.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45 entries, 0 to 44
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Store   45 non-null     int64
 1   Type    45 non-null     object
 2   Size    45 non-null     int64
dtypes: int64(2), object(1)
memory usage: 1.2+ KB

In [16]:
# Number of Missing Values
sales.isnull().sum()

Store           0
Dept            0
Date            0
Weekly_Sales    0
IsHoliday       0
dtype: int64

In [17]:
features.isnull().sum()

Store              0
Date               0
Temperature        0
Fuel_Price         0
MarkDown1       4158
MarkDown2       5269
MarkDown3       4577
MarkDown4       4726
MarkDown5       4140
CPI              585
Unemployment     585
IsHoliday          0
dtype: int64

In [18]:
stores.isnull().sum()

Store    0
Type     0
Size     0
dtype: int64

In [19]:
# Statistical summary
sales.describe()

               Store           Dept   Weekly_Sales
count  421570.000000  421570.000000  421570.000000
mean       22.200546      44.260317   15981.258123
std        12.785297      30.492054   22711.183519
min         1.000000       1.000000   -4988.940000
25%        11.000000      18.000000    2079.650000
50%        22.000000      37.000000    7612.030000
75%        33.000000      74.000000   20205.852500
max        45.000000      99.000000  693099.360000

In [20]:
features.describe()

,Store,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment
count,8190.000000,8190.000000,8190.000000,4032.000000,2921.000000,3613.000000,3464.000000,4050.000000,7605.000000,7605.000000
mean,23.000000,59.356198,3.405992,7032.371786,3384.176594,1760.100180,3292.935886,4132.216422,172.460809,7.826821
std,12.987966,18.678607,0.431337,9262.747448,8793.583016,11276.462208,6792.329861,13086.690278,39.738346,1.877259
min,1.000000,-7.290000,2.472000,-2781.450000,-265.760000,-179.260000,0.220000,-185.170000,126.064000,3.684000
25%,12.000000,45.902500,3.041000,1577.532500,68.880000,6.600000,304.687500,1440.827500,132.364839,6.634000
50%,23.000000,60.710000,3.513000,4743.580000,364.570000,36.260000,1176.425000,2727.135000,182.764003,7.806000
75%,34.000000,73.880000,3.743000,8923.310000,2153.350000,163.150000,3310.007500,4832.555000,213.932412,8.567000
max,45.000000,101.950000,4.468000,103184.980000,104519.540000,149483.310000,67474.850000,771448.100000,228.976456,14.313000

In [21]:
stores.describe()

           Store           Size
count  45.000000      45.000000
mean   23.000000  130287.600000
std    13.133926   63825.271991
min     1.000000   34875.000000
25%    12.000000   70713.000000
50%    23.000000  126512.000000
75%    34.000000  202307.000000
max    45.000000  219622.000000

In [22]:
#duplicate
sales.duplicated().sum()

np.int64(0)

In [23]:
features.duplicated().sum()

np.int64(0)

In [24]:
stores.duplicated().sum()

np.int64(0)

In [25]:
#negative values in Weekly-Sales(table-sales data)
(sales['Weekly_Sales'] < 0).sum()

np.int64(1285)

In [26]:
sales[sales['Weekly_Sales'] < 0].head()

      Store  Dept        Date  Weekly_Sales  IsHoliday
846       1     6  10/08/2012       -139.65      False
2384      1    18  04/05/2012         -1.27      False
6048      1    47  19/02/2010       -863.00      False
6049      1    47  12/03/2010       -698.00      False
6051      1    47  08/10/2010        -58.00      False

In [27]:
# % of negative values
negative_count = (sales['Weekly_Sales'] < 0).sum()
total_count = sales.shape[0]

negative_percentage = (negative_count / total_count) * 100

negative_percentage

np.float64(0.30481296107408024)

In [28]:
(features['Temperature'] < 0).sum()

np.int64(4)

In [29]:
features[features['Temperature'] < 0].head()

,Store,Date,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment,IsHoliday
1144,7,04/02/2011,-2.06,3.011,NaN,NaN,NaN,NaN,NaN,191.762589,8.818,False
1244,7,04/01/2013,-6.08,3.034,1390.63,11904.04,37.82,65.08,1446.44,200.394083,7.107,False
1245,7,11/01/2013,-6.61,2.957,2117.01,8298.08,8.61,15.26,745.42,200.619091,7.107,False
1246,7,18/01/2013,-7.29,2.889,6630.25,3626.32,1.96,1174.23,1513.31,200.738262,7.107,False

In [30]:
# % of negative values
negative_count = (features['Temperature'] < 0).sum()
total_count = features.shape[0]

negative_percentage = (negative_count / total_count) * 100

negative_percentage

np.float64(0.04884004884004884)

In [31]:
(features['MarkDown1'] < 0).sum()

np.int64(4)

In [32]:
features[features['MarkDown1'] < 0].head()

,Store,Date,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment,IsHoliday
4162,23,15/02/2013,25.39,3.807,-563.90,2825.54,21.0,5510.21,4677.39,138.900429,3.932,False
5437,30,22/02/2013,49.09,3.597,-2781.45,297.30,NaN,NaN,791.67,224.054703,6.237,False
6514,36,09/11/2012,68.58,3.313,-16.93,850.05,NaN,NaN,733.24,222.150626,6.228,False
6518,36,07/12/2012,68.04,3.204,-772.21,NaN,NaN,NaN,692.10,222.325549,6.228,False

In [33]:
# % of negative values
negative_count = (features['MarkDown1'] < 0).sum()
total_count = features.shape[0]

negative_percentage = (negative_count / total_count) * 100

negative_percentage

np.float64(0.04884004884004884)

In [34]:
(features['MarkDown2'] < 0).sum()

np.int64(25)

In [35]:
features[features['MarkDown2'] < 0].head()

,Store,Date,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment,IsHoliday
657,4,23/03/2012,59.07,3.759,8806.80,-10.50,5.99,739.14,4396.97,130.896645,4.607,False
860,5,17/08/2012,87.52,3.571,1649.56,-10.98,2.31,1955.75,1205.23,222.627675,5.603,False
873,5,16/11/2012,56.89,3.252,1631.01,-35.74,15.46,326.59,2310.83,224.106624,5.422,False
1265,7,31/05/2013,50.70,3.870,2350.78,-7.76,91.59,166.86,540.89,NaN,NaN,False
1587,9,10/08/2012,88.66,3.494,3180.78,-9.94,1.40,2112.03,2314.58,225.717009,5.277,False

In [36]:
# % of negative values
negative_count = (features['MarkDown2'] < 0).sum()
total_count = features.shape[0]

negative_percentage = (negative_count / total_count) * 100

negative_percentage

np.float64(0.3052503052503053)

In [37]:
(features['MarkDown3'] < 0).sum()

np.int64(13)

In [38]:
features[features['MarkDown3'] < 0].head()

,Store,Date,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment,IsHoliday
1063,6,11/01/2013,48.26,3.243,5510.29,33063.57,-0.86,693.10,3418.77,225.832011,5.372,False
1611,9,25/01/2013,49.14,3.227,200.46,348.20,-14.29,59.00,2162.77,228.030618,5.049,False
1615,9,22/02/2013,45.91,3.597,2810.86,1405.04,-179.26,63.12,3593.56,228.205445,5.049,False
2337,13,11/01/2013,20.00,2.982,3726.82,17212.29,-23.97,116.72,2662.80,131.957000,5.372,False
3978,22,01/02/2013,32.63,3.608,19102.16,1403.25,-89.10,43742.76,1549.09,142.868066,7.328,False

In [39]:
# % of negative values
negative_count = (features['MarkDown3'] < 0).sum()
total_count = features.shape[0]

negative_percentage = (negative_count / total_count) * 100

negative_percentage

np.float64(0.15873015873015872)

In [40]:
(features['MarkDown5'] < 0).sum()

np.int64(2)

In [41]:
features[features['MarkDown5'] < 0].head()

,Store,Date,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment,IsHoliday
893,5,05/04/2013,61.88,3.583,9023.29,927.32,170.24,405.30,-185.17,225.682320,5.278,False
5785,32,02/11/2012,46.32,3.604,11156.55,5943.82,24.22,441.71,-37.02,199.290867,7.557,False

In [42]:
# % of negative values
negative_count = (features['MarkDown5'] < 0).sum()
total_count = features.shape[0]

negative_percentage = (negative_count / total_count) * 100

negative_percentage

np.float64(0.02442002442002442)

STEP 3: Data Cleaning

In [44]:
# Date Fixing
sales['Date'] = pd.to_datetime(sales['Date'], dayfirst=True)
features['Date'] = pd.to_datetime(features['Date'], dayfirst=True)

In [45]:
# Delete Negative values in Weekly_sales
sales = sales[sales['Weekly_Sales'] >= 0]

In [46]:
# Negative values in Markdown 1,2,3,5
markdown_cols = ['MarkDown1','MarkDown2','MarkDown3','MarkDown5']

for col in markdown_cols:
    features[col] = features[col].apply(lambda x: 0 if x < 0 else x)

In [47]:
# Missing values in Markdawns, CPI, Unemployment
markdown_cols = ['MarkDown1','MarkDown2','MarkDown3','MarkDown4','MarkDown5']
features[markdown_cols] = features[markdown_cols].fillna(0)

features['CPI'] = features['CPI'].fillna(features['CPI'].mean())
features['Unemployment'] = features['Unemployment'].fillna(features['Unemployment'].mean())

In [48]:
# Sorting
sales = sales.sort_values(by='Date')
features = features.sort_values(by='Date')

STEP 4: Verification

In [52]:
# Missing Values
sales.isnull().sum()

Store           0
Dept            0
Date            0
Weekly_Sales    0
IsHoliday       0
dtype: int64

In [50]:
features.isnull().sum()

Store           0
Date            0
Temperature     0
Fuel_Price      0
MarkDown1       0
MarkDown2       0
MarkDown3       0
MarkDown4       0
MarkDown5       0
CPI             0
Unemployment    0
IsHoliday       0
dtype: int64

In [51]:
stores.isnull().sum()

Store    0
Type     0
Size     0
dtype: int64

In [53]:
# Data Type
sales.info()

<class 'pandas.core.frame.DataFrame'>
Index: 420285 entries, 0 to 421569
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Store         420285 non-null  int64
 1   Dept          420285 non-null  int64
 2   Date          420285 non-null  datetime64[ns]
 3   Weekly_Sales  420285 non-null  float64
 4   IsHoliday     420285 non-null  bool
dtypes: bool(1), datetime64[ns](1), float64(1), int64(2)
memory usage: 16.4 MB

In [54]:
features.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8190 entries, 0 to 8189
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Store         8190 non-null   int64
 1   Date          8190 non-null   datetime64[ns]
 2   Temperature   8190 non-null   float64
 3   Fuel_Price    8190 non-null   float64
 4   MarkDown1     8190 non-null   float64
 5   MarkDown2     8190 non-null   float64
 6   MarkDown3     8190 non-null   float64
 7   MarkDown4     8190 non-null   float64
 8   MarkDown5     8190 non-null   float64
 9   CPI           8190 non-null   float64
 10  Unemployment  8190 non-null   float64
 11  IsHoliday     8190 non-null   bool
dtypes: bool(1), datetime64[ns](1), float64(9), int64(1)
memory usage: 775.8 KB

In [55]:
stores.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45 entries, 0 to 44
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Store   45 non-null     int64
 1   Type    45 non-null     object
 2   Size    45 non-null     int64
dtypes: int64(2), object(1)
memory usage: 1.2+ KB

In [56]:
# Negative Values
(sales['Weekly_Sales'] < 0).sum()

np.int64(0)

In [57]:
(features['Temperature'] < 0).sum()

np.int64(4)

In [58]:
(features['MarkDown1'] < 0).sum()

np.int64(0)

In [59]:
(features['MarkDown2'] < 0).sum()

np.int64(0)

In [60]:
(features['MarkDown3'] < 0).sum()

np.int64(0)

In [61]:
(features['MarkDown4'] < 0).sum()

np.int64(0)

In [62]:
(features['MarkDown5'] < 0).sum()

np.int64(0)

In [63]:
# Number of Raws
sales.shape

(420285, 5)

In [64]:
features.shape

(8190, 12)

In [65]:
stores.shape

(45, 3)

In [68]:
# Date
sales['Date'].min(), sales['Date'].max()

(Timestamp('2010-02-05 00:00:00'), Timestamp('2012-10-26 00:00:00'))

In [69]:
features['Date'].min(), features['Date'].max()

(Timestamp('2010-02-05 00:00:00'), Timestamp('2013-07-26 00:00:00'))

In [70]:
# Outliers
sales.describe()

,Store,Dept,Date,Weekly_Sales
count,420285.000000,420285.000000,420285,420285.000000
mean,22.195477,44.242771,2011-06-18 07:22:30.395088384,16030.329773
min,1.000000,1.000000,2010-02-05 00:00:00,0.000000
25%,11.000000,18.000000,2010-10-08 00:00:00,2117.560000
50%,22.000000,37.000000,2011-06-17 00:00:00,7659.090000
75%,33.000000,74.000000,2012-02-24 00:00:00,20268.380000
max,45.000000,99.000000,2012-10-26 00:00:00,693099.360000
std,12.787213,30.507197,NaN,22728.500149

In [71]:
features.describe()

,Store,Date,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment
count,8190.000000,8190,8190.000000,8190.000000,8190.000000,8190.000000,8190.000000,8190.000000,8190.000000,8190.000000,8190.000000
mean,23.000000,2011-10-31 12:00:00,59.356198,3.405992,3462.595547,1207.059049,776.513540,1392.763115,2043.430855,172.460809,7.826821
min,1.000000,2010-02-05 00:00:00,-7.290000,2.472000,0.000000,0.000000,0.000000,0.000000,0.000000,126.064000,3.684000
25%,12.000000,2010-12-17 00:00:00,45.902500,3.041000,0.000000,0.000000,0.000000,0.000000,0.000000,132.653774,6.833000
50%,23.000000,2011-10-31 12:00:00,60.710000,3.513000,0.000000,0.000000,0.000000,0.000000,0.000000,172.460809,7.826821
75%,34.000000,2012-09-14 00:00:00,73.880000,3.743000,4639.585000,98.590000,24.220000,774.692500,2680.295000,212.766994,8.519000
max,45.000000,2013-07-26 00:00:00,101.950000,4.468000,103184.980000,104519.540000,149483.310000,67474.850000,771448.100000,228.976456,14.313000
std,12.987966,NaN,18.678607,0.431337,7388.608211,5495.537791,7539.948322,4707.111488,9431.217105,38.292649,1.808963

In [72]:
# Unique
sales['Store'].nunique()

45

In [73]:
features['Store'].nunique()

45

In [74]:
stores['Store'].nunique()

45

In [75]:
# Relations
set(sales['Store']) - set(stores['Store'])

set()

STEP 5: Saving

In [76]:
sales.to_csv("sales_cleaned.csv", index=False)

In [77]:
features.to_csv("features_cleaned.csv", index=False)

In [78]:
stores.to_csv("stores_cleaned.csv", index=False)

In [79]:
# Merge
df = sales.merge(features, on=['Store','Date','IsHoliday'], how='left')

In [80]:
df = df.merge(stores, on='Store', how='left')

In [82]:
df.shape

(420285, 16)

In [83]:
df.isnull().sum()

Store           0
Dept            0
Date            0
Weekly_Sales    0
IsHoliday       0
Temperature     0
Fuel_Price      0
MarkDown1       0
MarkDown2       0
MarkDown3       0
MarkDown4       0
MarkDown5       0
CPI             0
Unemployment    0
Type            0
Size            0
dtype: int64

In [84]:
df.head()

,Store,Dept,Date,Weekly_Sales,IsHoliday,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment,Type,Size
0,1,1,2010-02-05,24924.50,False,42.31,2.572,0.0,0.0,0.0,0.0,0.0,211.096358,8.106,A,151315
1,23,79,2010-02-05,35265.03,False,15.25,2.788,0.0,0.0,0.0,0.0,0.0,131.527903,5.892,B,114533
2,23,78,2010-02-05,12.00,False,15.25,2.788,0.0,0.0,0.0,0.0,0.0,131.527903,5.892,B,114533
3,20,5,2010-02-05,56536.02,False,25.92,2.784,0.0,0.0,0.0,0.0,0.0,204.247194,8.187,A,203742
4,16,32,2010-02-05,3852.56,False,19.79,2.580,0.0,0.0,0.0,0.0,0.0,189.381697,7.039,B,57197

In [85]:
df = df.sort_values(by='Date')

In [86]:
df.to_csv("retail_final_dataset.csv", index=False)